#!/usr/bin/env bash
# scripts/secrets.sh — Sustainable secrets management for the Chess Platform.
#
# Usage:
#   ./scripts/secrets.sh init          Generate a local .env file with strong random credentials.
#   ./scripts/secrets.sh k8s-apply     Create/update the chess-secrets K8s Secret from .env.
#   ./scripts/secrets.sh k8s-rotate    Rotate production secrets and rolling-restart pods.
#
# Design:
#   - Secrets are NEVER stored in Git. .env is gitignored, K8s Secrets live in the cluster.
#   - This script is the ONLY place credentials are generated or applied.
#   - Production values are injected into K8s via `kubectl create secret`, not YAML files.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

NAMESPACE="${K8S_NAMESPACE:-chess}"

rand_hex() { openssl rand -hex "$1"; }
rand_b64() { openssl rand -base64 "$1" | tr -d '/+=' | head -c "$1"; }

cmd_init() {
    if [ -f .env ]; then
        printf "${YELLOW}⚠  .env already exists. Overwrite? [y/N]: ${NC}"
        read -r confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 0
        fi
    fi

    cat > .env <<EOF
# Auto-generated by scripts/secrets.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file.

POSTGRES_USER=chess_$(rand_hex 4)
POSTGRES_PASSWORD=$(rand_hex 24)
POSTGRES_DB=chess_$(rand_hex 4)
JWT_SECRET=$(rand_b64 48)
EOF

    chmod 600 .env
    printf "${GREEN}✔  .env created with strong random credentials.${NC}\n"
    printf "   File permissions set to 600 (owner-only).\n"
}

cmd_k8s_apply() {
    if [ ! -f .env ]; then
        printf "${RED}✘  No .env file found. Run 'just secrets-init' first.${NC}\n"
        exit 1
    fi

    # Source the .env file
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a

    # Validate required vars
    for var in POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB JWT_SECRET; do
        if [ -z "${!var:-}" ]; then
            printf "${RED}✘  Missing required variable: %s${NC}\n" "$var"
            exit 1
        fi
    done

    DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@chess-db:5432/${POSTGRES_DB}?sslmode=disable"

    kubectl create secret generic chess-secrets \
        --namespace="$NAMESPACE" \
        --from-literal="postgres-password=${POSTGRES_PASSWORD}" \
        --from-literal="jwt-secret=${JWT_SECRET}" \
        --from-literal="database-url=${DATABASE_URL}" \
        --dry-run=client -o yaml | kubectl apply -f -

    printf "${GREEN}✔  chess-secrets applied to namespace '%s'.${NC}\n" "$NAMESPACE"
}

cmd_k8s_rotate() {
    printf "${YELLOW}⚠  This will generate NEW secrets and rolling-restart all pods.${NC}\n"
    printf "   Continue? [y/N]: "
    read -r confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    # Generate fresh .env
    cmd_init

    # Apply to cluster
    cmd_k8s_apply

    # Rolling restart
    kubectl rollout restart deployment chess-api chess-worker chess-db \
        --namespace="$NAMESPACE" 2>/dev/null || true

    printf "${GREEN}✔  Secrets rotated and pods restarting.${NC}\n"
}

# --- Entrypoint ---
case "${1:-help}" in
    init)       cmd_init ;;
    k8s-apply)  cmd_k8s_apply ;;
    k8s-rotate) cmd_k8s_rotate ;;
    *)
        echo "Usage: $0 {init|k8s-apply|k8s-rotate}"
        echo ""
        echo "  init        Generate a local .env with strong random credentials"
        echo "  k8s-apply   Create/update chess-secrets K8s Secret from .env"
        echo "  k8s-rotate  Rotate all secrets and rolling-restart pods"
        exit 1
        ;;
esac
