apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-db
spec:
  serviceName: "{{ .Chart.Name }}-db"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
spec:
  selector:
    app: {{ .Chart.Name }}-db
  ports:
  - protocol: TCP
    port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
